[package]
name = "zeroos-vfs"
version = "0.1.0"
edition = "2021"

[dependencies]
foundation = { workspace = true, default-features = false, features = ["vfs"] }
libc = { workspace = true }

[features]
default = []
